import '../globals.scss';
import styles from './layout.module.scss';
import cn from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from './components/Sidebar/Sidebar';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className={styles.wrapper}>
					<Header className={styles.header}></Header>
					<Sidebar className={styles.sidebar}></Sidebar>
					<div className={styles.body}>{children}</div>
					<Footer className={styles.footer}></Footer>
				</div>
			</body>
		</html>
	);
}
