import styles from '../page.module.scss';
import { GetStaticProps, Metadata } from 'next';
import Button from '../components/Button/Button';
import Paragraph from '../components/Paragraph/Paragraph';
import Tag from '../components/Tag/Tag';
import Rating from '../components/Rating/Rating';
import React from 'react';
import { Menu } from '../components/Menu/Menu';
import axios from 'axios';
import { MenuItem } from '@/interfaces/menu.interface';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Home() {
	
	return (
		<main className={styles.main}>
			<div className={styles.container}>Главная страница</div>
			<Menu />
			<Button arrow='right' appearance='primary'>
				Button
			</Button>
			<Button arrow='down' appearance='ghost'>
				Button
			</Button>
			<Paragraph size='large'>dsada</Paragraph>
			<Paragraph size='small'>dsada</Paragraph>
			<Paragraph>dsada</Paragraph>
			<Tag size='small' color='green'>
				asdas
			</Tag>
			<Tag size='regular' color='primary'>
				asdas
			</Tag>
			<Tag color='red' href='google.com'>
				asdas
			</Tag>
			<Tag color='ghost'>asdas</Tag>
			<Rating isEditable={true} />
		</main>
	);
}

interface HomeProps {
	data: MenuItem[];
	firstCategory: number;
}
