import styles from '../../page.module.scss';
import { Metadata } from 'next';
import Tag from '../../components/Tag/Tag';
import Rating from '../../components/Rating/Rating';
import React, { useState } from 'react';
import { Menu } from '@/app/components/Menu/Menu';

export const metadata: Metadata = {
	title: 'About',
	description: 'Generated by create next app',
};

export default function About(): JSX.Element {
	// const [rating, setRating] = useState<number>(4);

	return (
		<div className={styles.main}>
			<div className={styles.container}>О Нас</div>
			<Tag size='small' color='green'>
				asdas
			</Tag>
			<Tag size='regular' color='primary'>
				asdas
			</Tag>
			<Tag color='red' href='google.com'>
				asdas
			</Tag>
			<Tag color='ghost'>asdas</Tag>
			{/* <Rating rating={4} isEditable={true} /> */}
		</div>
	);
}
