'use client';

import styles from './page.module.scss';
import { Metadata } from 'next';
import Button from './components/Button/Button';
import Paragraph from './components/Paragraph/Paragraph';
import Tag from './components/Tag/Tag';
import Rating from './components/Rating/Rating';
import React, { useState } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Home(): JSX.Element {
	const [rating, setRating] = useState<number>(4);

	return (
		<main className={styles.main}>
			<div className={styles.container}>container</div>
			<Button arrow='right' appearance='primary'>
				Button
			</Button>
			<Button arrow='down' appearance='ghost'>
				Button
			</Button>
			<Paragraph size='large'>dsada</Paragraph>
			<Paragraph size='small'>dsada</Paragraph>
			<Paragraph>dsada</Paragraph>
			<Tag size='small' color='green'>
				asdas
			</Tag>
			<Tag size='regular' color='primary'>
				asdas
			</Tag>
			<Tag color='red' href='google.com'>
				asdas
			</Tag>
			<Tag color='ghost'>asdas</Tag>
			<Rating rating={rating} isEditable={true} setRating={setRating} />
		</main>
	);
}
