import styles from './page.module.scss';
import { Metadata } from 'next';
import Button from './components/Button/Button';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Home(): JSX.Element {
	return (
		<main className={styles.main}>
			<div className={styles.container}>container</div>
			<Button arrow='right' appearance='primary'>
				Button
			</Button>
			<Button arrow='down' appearance='ghost'>
				Button
			</Button>
		</main>
	);
}
