import styles from '../../page.module.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Login',
	description: 'Generated by create next app',
};

export default function Login(): JSX.Element {
	return <div className={styles.main}>Login</div>;
}
